MCOL-1734 CS now behaves similar to MDB in case of NOT IN + correlated subquery if the subquery returns empty set.
mariadb-corporation/mariadb-columnstore-engine pull request #1000
Opened 2020-01-07 14:27 UTC by drrtuy

CS now returns full outer record set.

gcc 8.2 complains about unused variable in ha_mcs_impl.cc

2020-01-07 16:36 UTC, pleblanc1976 requested changes
Roman will add similar code for um joins

2020-01-07 22:41 UTC, pleblanc1976 commented
Be sure to add a query or two to the regression test for this one.

2020-01-10 12:50 UTC, LinuxJedi approved these changes

2020-01-14 16:43 UTC, pleblanc1976 commented
Update on this one?  Does disk-join produce correct results?

2020-01-14 23:26 UTC, drrtuy commented
Yes, UM-side memory and disk based joins also produce expected results.

вт, 14 янв. 2020 г. в 19:43, Patrick LeBlanc <notifications@github.com>:

> Update on this one? Does disk-join produce correct results?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mariadb-corporation/mariadb-columnstore-engine/pull/1000?email_source=notifications&email_token=AC3JDLBSEBOKUVDFDRJR5TTQ5XTRTA5CNFSM4KD2BNM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI5JO6A#issuecomment-574265208>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC3JDLET4CDYPZWW73BEJMTQ5XTRTANCNFSM4KD2BNMQ>
> .
>

2020-01-15 04:28 UTC, pleblanc1976 approved these changes

2020-01-15 04:28 UTC, merged