MCOL-3769 Refactored create_SH() to avoid error-prone fallback to
mariadb-corporation/mariadb-columnstore-engine pull request #1095
Opened 2020-03-07 16:27 UTC by drrtuy

other execution paths after CS applies some optimizations.

Add meaningfull errors to describe optimization rewrite failures.

2020-03-11 15:41 UTC, tntnatbry requested changes
Similar comments to https://github.com/mariadb-corporation/mariadb-columnstore-engine/pull/1094 also apply here.

2020-03-18 15:51 UTC, tntnatbry requested changes

2020-03-18 15:51 UTC, tntnatbry commented on dbcon/mysql/ha_mcs_pushdown.cpp
> +  rewrite_error= 0;
= false;

2020-03-18 15:51 UTC, tntnatbry commented on dbcon/mysql/ha_mcs_pushdown.cpp
> +            handler->err_msg.assign("create_columnstore_select_handler(): Internal error happens in SL::handle_derived()");
occurred here instead of happens :)

2020-03-18 15:51 UTC, tntnatbry commented on dbcon/mysql/ha_mcs_pushdown.cpp
> +            handler->err_msg.assign("create_columnstore_select_handler: Internal error happens in optimize_unflattened_subqueries_mcs()");
occurred instead of happens

2020-03-18 17:47 UTC, drrtuy commented
I pushed the changes into a wrong remote. Now should be fine.

2020-03-18 18:36 UTC, tntnatbry approved these changes

2020-03-18 18:37 UTC, merged