MCOL-4000 Allow columnstore_use_import_for_batchinsert to use a new value, ALWAYS.
mariadb-corporation/mariadb-columnstore-engine pull request #1202
Opened 2020-05-12 23:53 UTC by tntnatbry

2020-05-13 15:11 UTC, tntnatbry commented
Please don't merge yet, I am adding tests cases to the regression suite for this.

2020-05-13 15:25 UTC, pleblanc1976 requested changes
Adding a safety net to block merging for now

2020-05-14 23:21 UTC, tntnatbry commented
Corresponding regression suite tests for this are in https://github.com/mariadb-corporation/mariadb-columnstore-regression-test/pull/224

2020-05-15 17:01 UTC, drrtuy approved these changes

2020-05-15 17:28 UTC, pleblanc1976 approved these changes

2020-05-15 17:28 UTC, merged