MCOL-3915 Update columnstore install and uninstall procedure
mariadb-corporation/mariadb-columnstore-engine pull request #1221
Opened 2020-05-22 23:14 UTC by jmrojas2332

Columnstore installation now leaves mariadb in the same state (active or inactive) as it was before installation. Columnstore properly cleans up log/tmp/share files during columnstore-pre-uninstall w/o the warnings from rpm.

Also did some cleanup.

2020-05-22 23:15 UTC, jmrojas2332 commented on cmake/cpackEngineRPM.cmake
> +SET(CPACK_RPM_columnstore-engine_PRE_INSTALL_SCRIPT_FILE ${CMAKE_SOURCE_DIR}/build/preInstall_storage_engine.sh)
Typo here, partly explains the case David Hall had where old columnstore was not cleaned up properly.

2020-05-22 23:16 UTC, jmrojas2332 commented on oam/install_scripts/columnstore-post-install.in
> +fi
startup mariadb if not already running. Need mariadb for some installation.

2020-05-22 23:17 UTC, jmrojas2332 commented on oam/install_scripts/columnstore-post-install.in
> -		cp @ENGINE_SUPPORTDIR@/mcs-primproc.service /usr/lib/systemd/system/. >/dev/null 2>&1
The formatting finally got to me so I did some cleanup since I was here

2020-05-22 23:19 UTC, jmrojas2332 commented on oam/install_scripts/columnstore-post-install.in
> +fi
Let us not forget to stop mariadb if we started it.

2020-05-22 23:20 UTC, jmrojas2332 commented on oam/install_scripts/columnstore-pre-uninstall.in
> +    clearShm  > /dev/null 2>&1
clearShm would have already been called during systemctl stop so only need this in here w/o systemd

2020-05-22 23:21 UTC, jmrojas2332 commented on oam/install_scripts/columnstore-pre-uninstall.in
> +fi
Let us make sure that an old systemd gets rid of running ProcMon/ProcMgr.
columnstore-pre-uninstall is also called during installation as a "pre-install" script.

2020-05-22 23:23 UTC, jmrojas2332 commented on oam/install_scripts/columnstore-pre-uninstall.in
> -rm -rf /usr/share/columnstore
No need for this. Will already be cleaned up during yum remove mariadb-columnstore

2020-05-22 23:24 UTC, jmrojas2332 commented on oam/install_scripts/columnstore-pre-uninstall.in
> -cp @ENGINE_SUPPORTDIR@/myCnf-include-args.text @ENGINE_SUPPORTDIR@/myCnf-include-args.text.rpmsave >& /dev/null
only file left in /usr/share/columnstore after package removal. I don't really think we need this if we do a removal.

2020-05-22 23:24 UTC, jmrojas2332 commented on oam/install_scripts/mcs-stop-controllernode.sh.in
> +while [ -n "$(pgrep -x controllernode)" ] && [ $timeout -gt 0 ]
Be safe here. If pgrep -x controllernode returns nothing it will not treat it as an empty string

2020-05-22 23:25 UTC, jmrojas2332 commented on oam/install_scripts/post-mysql-install
> -
Moved a variation of this to columnstore-post-install w/o skip-grant-tables

2020-05-22 23:25 UTC, jmrojas2332 commented on oamapps/postConfigure/helpers.cpp
> +        passwordOption = " --password=" + mysqlpw;
minor cleanup

2020-05-22 23:25 UTC, jmrojas2332 commented on oamapps/postConfigure/postConfigure.cpp
> +	cmd = "columnstore_installer dummy.rpm dummy.rpm dummy.rpm dummy.rpm dummy.rpm initial dummy n --nodeps ' ' 1 " + numBlocksPctParam + " " + totalUmMemoryParam;
cleanup postconfigure some more

2020-05-22 23:29 UTC, jmrojas2332 commented on oam/install_scripts/columnstore-post-install.in
> +fi
Need to test this on non-systemd mariadb. Don't merge unless you're sure this works. we are starting mysqld_safe so i need to make sure this doesn't need to change.

2020-05-26 02:56 UTC, jmrojas2332 commented on oam/install_scripts/columnstore-post-install.in
> +fi
Confirmed system works as expected when mariadb system unit does not exist

2020-05-26 02:56 UTC, jmrojas2332 commented
I have tested on both a system with a mariadb systemd unit and without a mariadb systemd unit.

2020-05-26 14:18 UTC, drrtuy requested changes

2020-05-26 14:18 UTC, drrtuy commented on dbcon/mysql/install_mcs_mysql.sh.in
> +su -s /bin/sh -c 'mysql < /tmp/123.sql'  mysql 2> ${tmpdir}/mysql_install.log <<EOD
This doesn't seem right. You need to replace /tmp/123.sql with the file or sqls we are executing.
I wonder if this works?

2020-05-26 14:18 UTC, drrtuy commented on oam/install_scripts/columnstore-post-install.in
> +            cp @ENGINE_SBINDIR@/columnstore /etc/init.d/. >/dev/null 2>&1
JFYI This script now effectively does nothing. We will put our automation start/stop in one and use it here.

2020-05-26 17:59 UTC, drrtuy commented on oam/install_scripts/columnstore-post-install.in
> +    systemctl cat mariadb.service > /dev/null 2>&1
I found out that service might be masked(/etc/systemd/system/mariadb.service is a symbolic link to /dev/null) but `systemctl cat mariadb.service` returns 0. I'll fix this after we merge this one.

2020-05-26 19:30 UTC, jmrojas2332 commented on dbcon/mysql/install_mcs_mysql.sh.in
> +su -s /bin/sh -c 'mysql < /tmp/123.sql'  mysql 2> ${tmpdir}/mysql_install.log <<EOD
I have applied the proper fix in the most recent commit and have tested install_mcs_mysql is working by removing schema associated with columnstore and reinstalling to confirm columnstore-related schema is created

2020-05-27 13:26 UTC, drrtuy approved these changes

2020-05-27 13:26 UTC, merged