MCOL-4012 Enable ColumnStore as a non root user
mariadb-corporation/mariadb-columnstore-engine pull request #1384
Opened 2020-08-26 18:36 UTC by jmrojas2332

Columnstore processes now run as user mysql by default, matching server.
Support for running columnstore processes as non-root added
Also includes a fix for systemd units starting before network is ready.

If possible we should get this into upcoming release as the last point is a bug a customer has run into already.

2020-08-31 16:18 UTC, drrtuy approved these changes

2020-08-31 19:32 UTC, pleblanc1976 requested changes

2020-08-31 19:32 UTC, pleblanc1976 commented on oam/install_scripts/columnstore-post-install.in
> +    chown -R mysql:mysql /var/lib/columnstore
Looks like a change was missed.

2020-09-02 15:13 UTC, pleblanc1976 approved these changes

2020-09-02 15:14 UTC, merged