MCOL-4361 Replace pow(10.0, (double)scale) expressions with a static …
mariadb-corporation/mariadb-columnstore-engine pull request #1856
Opened 2021-04-09 08:24 UTC by abarkov

…dictionary lookup.

2021-04-12 10:17 UTC, tntnatbry requested changes

2021-04-12 10:17 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +                        auto d = in.getScaledSInt64FieldAsXFloat<double>(i);
Shouldn't the template parameter be `float` here?

2021-04-12 10:17 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +                        auto d = in.getScaledUInt64FieldAsXFloat<double>(i);
I think the template parameter should be changed to `float`.

2021-04-12 10:17 UTC, tntnatbry commented on utils/rowgroup/rowaggregation.cpp
> +                valIn = rowIn.getScaledSInt64FieldAsXFloat<long double>(colIn, scale);
Similar to previous client calls, we can just use `getScaledSInt64FieldAsXFloat<long double>(colIn)` here.

2021-04-12 10:17 UTC, tntnatbry commented on utils/rowgroup/rowaggregation.cpp
> +                valIn = rowIn.getScaledSInt64FieldAsXFloat<long double>(colIn, scale);
Similar to previous client calls, we can just use `getScaledSInt64FieldAsXFloat<long double>(colIn)` here.

2021-04-12 10:17 UTC, tntnatbry commented on utils/rowgroup/rowaggregation.cpp
> +                valIn = rowIn.getScaledSInt64FieldAsXFloat<long double>(colIn, scale);
Similar to previous client calls, we can just use `getScaledSInt64FieldAsXFloat<long double>(colIn)` here.

2021-04-12 10:17 UTC, tntnatbry commented on utils/udfsdk/udfsdk.cpp
> +                op2.value *= datatypes::scaleDivisor<int64_t>((uint32_t) (op2.scale - op1.scale));
In the above two changes, if the subtraction of the scales results in a negative value, op1.value or op2.value is basically set to 0. The new code is changing this behaviour.

2021-04-13 05:27 UTC, abarkov commented on dbcon/joblist/tupleunion.cpp
> +                        auto d = in.getScaledSInt64FieldAsXFloat<double>(i);
As discussed on Slask, this expression:
```
(gdb) p (float) (89999999999/(float) 100000000000)
$4 = 0.900000036
```
would return a less precise result than
```
(gdb) p (float) (89999999999/(double) 100000000000)
$5 = 0.899999976
```

The problem is that conversion of the divisor (which is stored as integer 100000000000)  to FLOAT is lossy, while conversion to DOUBLE is precise.

2021-04-13 05:28 UTC, abarkov commented on dbcon/joblist/tupleunion.cpp
> +                        auto d = in.getScaledUInt64FieldAsXFloat<double>(i);
same here

2021-04-13 11:01 UTC, tntnatbry approved these changes

2021-04-13 11:01 UTC, merged