A plugable PoorManProfiler singleton
mariadb-corporation/mariadb-columnstore-engine pull request #1863
Opened 2021-04-13 16:30 UTC by drrtuy

2021-04-13 17:04 UTC, mariadb-AlexeyAntipovsky requested changes

2021-04-13 17:04 UTC, mariadb-AlexeyAntipovsky commented on primitives/primproc/primitiveserver.h
> +#define PRIMPROC_STOPWATCH
Is it really needed to be set in production?

2021-04-13 17:04 UTC, mariadb-AlexeyAntipovsky commented on utils/loggingcpp/poormanprofiler.inc
> +#define POORMANPROFILER
Guard name mismatch

2021-04-13 17:04 UTC, mariadb-AlexeyAntipovsky commented on utils/loggingcpp/poormanprofiler.inc
> +            stopwatchMapIter++;
I'm afraid there may be race condition here (i.e. in the case when inserting into the unordered_map from another thread will cause rehashing)

2021-04-13 17:04 UTC, mariadb-AlexeyAntipovsky commented on utils/loggingcpp/poormanprofiler.inc
> +    auto stopwatchMapIter = stopwatchMap.find(pthread_self());
And here too...

2021-04-13 17:06 UTC, drrtuy commented on primitives/primproc/primitiveserver.h
> +#define PRIMPROC_STOPWATCH
Surely not.

2021-04-16 09:19 UTC, mariadb-AlexeyAntipovsky approved these changes

2021-04-16 10:51 UTC, merged