Mcol 4673 regression cal show partition returns na
mariadb-corporation/mariadb-columnstore-engine pull request #1891
Opened 2021-04-26 13:18 UTC by mariadb-SergeyZefirov

The tricky part here is to 1) keep dropped ranged dropped and 2) keep set ranges set. The first part should be compatible with cpimport which utilizes dropping ranges to CP_UPDATING state and then to CP_VALID/CP_INVALID.

This is why we keep CP_UPDATING state notwithstanding that CP_INVALID is pretty sufficient for all purposes.

2021-04-27 05:43 UTC, abarkov commented
Sergey, please squish the changes into a single commit.
Enabling udf_calshowpartitions.test for `mtr --extern` looks Ok for me.

I can't say anything for the code change as I'm not strong with that part of the code.

2021-04-27 12:52 UTC, mariadb-SergeyZefirov commented
> Sergey, please squish the changes into a single commit.

Done!

> Enabling udf_calshowpartitions.test for `mtr --extern` looks Ok for me.
> 
> I can't say anything for the code change as I'm not strong with that part of the code.

Let me explain a bit - for you or for others who may be interested.

cpimport and write engine as a whole marks extents as UPDATING during update operation. Old version of code, prior to MCOL-2044, was marking these extents as UPDATING and then marked them as INVALID during final stage - this is what invalidateuncommittedExtents does.

Prior to MCOL-2044, it was done unconditionally, for both COMMIT and ROLLBACK operations. MCOL-2044 introduced keeping of ranges and blindly dropping ranges to INVALID stand in the way of the ultimate goal of I/O reduction.

So I put invalidateUncommittedExtents under condition of "NOT COMMIT" operation and that change left some of the extents marked as UPDATING as, well, UPDATING.

The scanning process in SELECT part of the test did not change UPDATING state to VALID state.

The calshowpartitions function does not distinguish between INVALID and UPDATING state and shows information for extents in these states as N/A. That is wrong.

So I changed the logic of invalidateUncommittedExtents to this: if extent was in UPDATING state, mark it INVALID. if extent in the VALID state (write engine has kept ranges up to date), do not mark it as INVALID.

In this case we have ranges kept and extents scans working properly.

2021-04-28 11:16 UTC, tntnatbry requested changes

2021-04-28 11:16 UTC, tntnatbry commented on versioning/BRM/extentmap.cpp
> +                    }
I am curious about this change. Shouldn't setting the below suffice for both narrow and wide cases:

```
fExtentMap[i].partition.cprange.bigLoVal = -1;
fExtentMap[i].partition.cprange.bigHiVal = 0;
```

2021-04-28 11:16 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/udf_calshowpartitions.test
>  DROP TABLE IF EXISTS t1;
Should we expand this test case to cover wide decimals?

2021-04-28 11:36 UTC, tntnatbry commented
@mariadb-SergeyZefirov At a high level, the change looks OK to me. I added a couple comments however.

I do have a question: As far as I understand, the goal of MCOL-2044 is to keep the extents in a VALID state during DML operations. The queries from MCOL-4673 issue description are the following:

```
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a DECIMAL(17,1)) ENGINE=ColumnStore;
INSERT INTO t1 VALUES (-8999999999999999.9);
SELECT * FROM t1 WHERE a=0;
SELECT calShowPartitions('t1','a');
```

Here, we create a single extent during the insert operation and set it to a VALID state of range (-8999999999999999.9,-8999999999999999.9)

So why would `calShowPartitions` return result as N/A, as in MCOL-4673?

2021-04-29 11:53 UTC, mariadb-SergeyZefirov reviewed
> @mariadb-SergeyZefirov At a high level, the change looks OK to me. I added a couple comments however.

Please, approve then.

> I do have a question: As far as I understand, the goal of MCOL-2044 is to keep the extents in a VALID state during DML operations. The queries from MCOL-4673 issue description are the following:

The correct wording would be "is **try** to keep extents in a VALID state" - it is not always possible, at least, not for all types of extents, thus we can only try.

> ```
> DROP TABLE IF EXISTS t1;
> CREATE TABLE t1 (a DECIMAL(17,1)) ENGINE=ColumnStore;
> INSERT INTO t1 VALUES (-8999999999999999.9);
> SELECT * FROM t1 WHERE a=0;
> SELECT calShowPartitions('t1','a');
> ```
> 
> Here, we create a single extent during the insert operation and set it to a VALID state of range (-8999999999999999.9,-8999999999999999.9)
> 
> So why would `calShowPartitions` return result as N/A, as in MCOL-4673?

The insert operation for single value does not do the extent keeping job - I overlooked that implementing MCOL-2044. It was a part of much needed refactoring but I was too tired to do that.

The extent(s) in single value insertion are marked as UPDATING (with a call to an ironically named function _markInvalid in extentmap.cpp) and should be brought to INVALID at the end of transaction, during COMMIT or ROLLBACK operations. The call is invalidateUncommittedExtents, with implementation in dbrm.cpp, I think.

The change in MCOL-2044 was to invalidate (set to INVALID state) extents conditionally, only not on COMMIT. This change left UPDATING extents marked as UPDATING after COMMIT.

Extent scan operations do not change extent state to VALID when extent is in UPDATING state. Thus, the SELECT query did not change extent state to VALID (from assumed INVALID).

As calShowPartitions does not discern between UPDATING and INVALID (it looks only for VALID value), the end result was N/A as for INVALID extents.

What I did in this change is to remove condition to call invalidateUncommittedExtents and to change behavior there: to mark INVALID only extents that were in UPDATING state.

This made subsequent scan operations to set ranges properly and test to pass.

2021-04-29 11:53 UTC, mariadb-SergeyZefirov commented on mysql-test/columnstore/basic/t/udf_calshowpartitions.test
>  DROP TABLE IF EXISTS t1;
I do not think so. I think expansion of the test suite is outside of scope of this PR.

2021-04-29 11:53 UTC, mariadb-SergeyZefirov commented on versioning/BRM/extentmap.cpp
> +                    }
Heh, being conditioned to work with CPMaxMin (where (u)int64_t ranges are separate from wide decimal ranges) I missed that EMCasualPartition does have both of them in unions.

I will change that, but I keep the comment - I have great confusion about uint128_t use. Unsigned DECIMAL(38) has range that is twice as small as signed DECIMAL(38) (0..10^38-1 and -(10^38-1)..10^38-1), they both inhabit int128_t. Roman specifically told me so.

2021-04-30 08:56 UTC, tntnatbry commented
@mariadb-SergeyZefirov Thanks for the explanation. Can you please fix the original commit message?

2021-04-30 09:00 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/udf_calshowpartitions.test
>  DROP TABLE IF EXISTS t1;
Ok. But I think this test case should be covered for wide decimals as well. If not in this PR, then separately and should probably go under the `mysql-test/columnstore/future`.

2021-05-24 09:10 UTC, drrtuy approved these changes

2021-05-24 09:10 UTC, merged