MCOL-4860 Remove All Legacy Variables From Columnstore.xml
mariadb-corporation/mariadb-columnstore-engine pull request #2094
Opened 2021-08-18 16:20 UTC by dhall-MariaDB

Also removed dead code in joblist. This code has been dead since InfiniDB 3.0 where the introduction of tupblebps deprecated it.

2021-08-19 17:29 UTC, dhall-MariaDB commented
Somethings breaking docker restart

2021-08-24 16:22 UTC, tntnatbry requested changes

2021-08-24 16:22 UTC, tntnatbry commented on oam/etc/Columnstore.xml
>  	</DMLProc>
Can you fix the indentation here?

2021-08-24 16:22 UTC, tntnatbry commented on oam/etc/Columnstore.xml
>          <TableLockSaveFile>/var/lib/columnstore/data1/systemFiles/dbrm/tablelocks</TableLockSaveFile>
Can you fix the indentation here?

2021-08-24 16:22 UTC, tntnatbry commented on oamapps/columnstoreSupport/mcsSupportUtil.cpp
>                      string amazonDeviceNameID = "PMVolumeAmazonDeviceName" + oam.itoa(*pt);
This line can also be removed.

2021-08-24 16:22 UTC, tntnatbry commented on oamapps/columnstoreSupport/mcsSupportUtil.cpp
>                  string amazonDeviceNameID = "PMVolumeAmazonDeviceName" + oam.itoa(*pt1);
This line can also be removed.

2021-08-24 16:22 UTC, tntnatbry commented on oam/etc/Columnstore.xml
> -		<ProfileFile>/etc/profile.d/columnstoreAlias.sh</ProfileFile>
Why is `ProfileFile` removed?

2021-08-24 16:22 UTC, tntnatbry commented on oam/etc/Columnstore.xml
> +        <TempFileCompressionType>Snappy</TempFileCompressionType> <!-- LZ4, Snappy -->
This needs more indentation.

2021-08-24 16:22 UTC, tntnatbry commented on oam/etc/Columnstore.xml
> +		<FifoSize>16</FifoSize>1
Typo, there is an extra 1 at the end.

2021-08-24 16:22 UTC, tntnatbry commented on dbcon/joblist/pdictionaryscan.cpp
> +}
References to planFlagsToPrimFlags should also be removed from:
tools/pingproc/pingproc.cpp

2021-08-24 16:22 UTC, tntnatbry commented on utils/winport/fixup.cpp
> -
Why is this code removed?

2021-08-24 16:22 UTC, tntnatbry commented on dbcon/joblist/primitivestep.h
> +    /** @brief constructor for completeBOPness
Looks like a typo here.

2021-08-24 16:22 UTC, tntnatbry commented on dbcon/joblist/primitivestep.h
> +class pColScanStep : public JobStep //, public PrimitiveMsg
Instead of commenting out, we should remove the code.

2021-08-24 16:22 UTC, tntnatbry commented on dbcon/joblist/primitivestep.h
> +     *setSingleThread
Looks like a typo.

2021-08-24 16:22 UTC, tntnatbry commented on dbcon/joblist/primitivestep.h
> -    void setOutputType(int8_t OutputType);
The field, `fOutputType` can also be removed from the class.

2021-08-24 16:22 UTC, tntnatbry commented on primitives/primproc/primproc.cpp
>      // We could use this same mechanism for other growing buffers.
Is the deleted out comment not relevant anymore?

2021-08-25 16:59 UTC, dhall-MariaDB commented on oam/etc/Columnstore.xml
> -		<ProfileFile>/etc/profile.d/columnstoreAlias.sh</ProfileFile>
Nowhere in C++ code is it used. Is it used from somewhere else?

2021-08-25 17:01 UTC, davidhall586 commented on dbcon/joblist/primitivestep.h
> +class pColScanStep : public JobStep //, public PrimitiveMsg
An oversight

2021-08-25 17:02 UTC, davidhall586 commented on primitives/primproc/primproc.cpp
>      // We could use this same mechanism for other growing buffers.
AggregationMemoryCheck is no longer a thing, so a comment referencing it could be confusing. It's possible that the work on MCOL-4626 might bring it back, but I'm not sure.

2021-08-25 17:49 UTC, drrtuy commented on oam/etc/Columnstore.xml
> +    <PMS2>
We don't need anything except PMS1 here b/c CMAPI takes care about multi-node cluster connections later.

2021-08-25 17:50 UTC, drrtuy commented on oam/etc/Columnstore.xml
> +        <ModuleDesc1>Director Module</ModuleDesc1>
We don't need sections for DMs.

2021-08-25 17:51 UTC, drrtuy commented on oam/etc/Columnstore.xml
> +    <DBRM_Worker2>
We need only DBRM_Worker1 in the default config. CMAPI takes care about others.

2021-08-25 17:52 UTC, drrtuy commented on oam/etc/Columnstore.xml
> +        <ServerTypeInstall>2</ServerTypeInstall>
We don't need this, Cloud, DataRedundancyConfig, DataRedundancyCopies, DataRedundancyStorageType.
mb DBRootStorageType.

2021-08-25 17:54 UTC, drrtuy commented on utils/winport/fixup.cpp
> -
B/c it belongs to the windows port. I doubt we will revive it.

2021-09-02 12:54 UTC, drrtuy requested changes
Plz address the comments.

2021-10-04 18:43 UTC, dhall-MariaDB commented on oam/etc/Columnstore.xml
> -		<ProfileFile>/etc/profile.d/columnstoreAlias.sh</ProfileFile>
ProfileFile is used by columnstoresupport. Since I want to revive the support report, we should probably add this back.

2022-03-04 14:53 UTC, closed without merging

2022-03-04 14:54 UTC, dhall-MariaDB commented
Replaced by https://github.com/mariadb-corporation/mariadb-columnstore-engine/pull/2302