MCOL-4874 Crossengine JOIN involving a ColumnStore table and a
mariadb-corporation/mariadb-columnstore-engine pull request #2169
Opened 2021-12-07 21:21 UTC by tntnatbry

wide decimal column in a non-ColumnStore table throws an exception.

ROW::getSignedNullValue() method does not support wide decimal fields
yet. To fix this exception, we remove the call to this method from
CrossEngineStep::setField().

2021-12-08 16:53 UTC, drrtuy commented on dbcon/joblist/crossenginestep.cpp
>  #ifdef _MSC_VER
Feel free to remove windows specific macros ifs.

2021-12-08 16:54 UTC, drrtuy commented on dbcon/joblist/crossenginestep.cpp
> +#if BOOST_VERSION >= 105200
What is the boost version that satisfies the condition?

2021-12-08 16:54 UTC, drrtuy commented on dbcon/joblist/crossenginestep.cpp
> +#if BOOST_VERSION >= 105200
Will we ever see it in the wild?

2021-12-08 17:26 UTC, drrtuy requested changes
Plz address the comments and convertValueNum() return type.

2021-12-08 18:02 UTC, tntnatbry commented
convertValueNum() return type has been updated. Please review. Regarding the if defs for Boost and Windows, I am reusing the code in dbcon/joblist/jlf_execplantojoblist.cpp::convertValueNum, these 2 functions should be consolidated to avoid code duplication.

2021-12-09 06:58 UTC, drrtuy approved these changes

2021-12-09 06:58 UTC, merged