Improved algorithm for STD/VAR functions
mariadb-corporation/mariadb-columnstore-engine pull request #2402
Opened 2022-06-01 21:12 UTC by mariadb-AndreyPiskunov

Welford's single-pass algorithm for STDDEV_SAMP, STDDEV_POP, VAR_POP, VAP_SAMP functions and window functions.
(ticket MCOL-5104). Also tests for them.

2022-06-02 13:56 UTC, mariadb-LeonidFedorov commented
@drrtuy take a note, this PR deletes ignore on ARM mtr tests, so we can have it full working

2022-06-03 10:23 UTC, drrtuy commented on utils/windowfunction/wf_stats.h
> +  long double fMean;
According with the styling guide new attributes must be prefixed with _ thus fM2sum_ is the name.

2022-06-03 10:24 UTC, drrtuy commented on utils/rowgroup/rowaggregation.cpp
> +  double block_count = rowIn.getDoubleField(colIn);
We use camel case for variable naming.

2022-06-03 10:25 UTC, drrtuy commented on mysql-test/columnstore/basic/r/std_aggregate_columnstore.result
> +DROP DATABASE IF EXISTS std_test_db;
The test should be removed b/c it is outside the scope of our control thus any related server change will break the test and we can do nothing with this.

2022-06-03 10:25 UTC, drrtuy requested changes
Thx for the patch. It is clean and nice.
Left some comments + discussed the patch offline.

2022-06-03 15:09 UTC, mariadb-LeonidFedorov approved these changes

2022-06-06 20:53 UTC, drrtuy approved these changes

2022-06-06 20:53 UTC, merged