[WIP] MCOL-5205 Fix bug from union type
mariadb-corporation/mariadb-columnstore-engine pull request #2526
Opened 2022-08-23 12:37 UTC by cakebytheoceanLuo

The Jira issue number for this PR is: [MCOL-5205](https://jira.mariadb.org/browse/MCOL-5205)

2022-08-24 19:59 UTC, tntnatbry requested changes

2022-08-24 19:59 UTC, tntnatbry commented on datatypes/mcs_datatype.h
> +inline bool isUnsignedInteger(const datatypes::SystemCatalog::ColDataType type)
To avoid code duplication, can you please use `isUnsignedInteger()` call in the above `isUnsigned()` function.

2022-08-24 19:59 UTC, tntnatbry commented on datatypes/mcs_datatype.h
> +      colWidth = 16;
Here, the precision should also be set, to `datatypes::INT128MAXPRECISION`, and the scale to 0.

2022-08-24 19:59 UTC, tntnatbry commented on utils/dataconvert/dataconvert.cpp
>            }
When `colDataType` is same, then the condition `type.colWidth > unionedType.colWidth` should be checked and should appropriately set the width.

2022-08-24 19:59 UTC, tntnatbry commented on utils/dataconvert/dataconvert.cpp
>            }
This does not handle all edge cases related to DECIMAL. For example the case when `type=DECIMAL` with width 2 bytes and `unionedType` was a BIGINT, this will incorrectly set the resulting `unionedType` to DECIMAL. Signedness and width should be appropriately considered for the case when `type` and/or `unionedType` are DECIMAL.

2022-08-24 19:59 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +SELECT * FROM (SELECT b FROM t1 UNION SELECT a FROM t1) tu ORDER BY b;
What is the point of the above 3 additions? They are repetitions of the previous 3 statements.

2022-08-24 19:59 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +SELECT * FROM (SELECT b FROM t1 UNION SELECT a FROM t1) tu ORDER BY b;
Just INSERT (-2, 2) at the start when the table is created, and remove the duplicated SELECTs.

2022-08-24 19:59 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +SELECT * FROM (SELECT * FROM t1 UNION SELECT * FROM t1) tu;
There should be an ORDER BY clause to make the result set deterministic.

2022-08-24 19:59 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +SELECT * FROM (SELECT * FROM t1 UNION SELECT * FROM t1) tu;
There should be an ORDER BY clause to make the result set deterministic.

2022-08-24 19:59 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +DROP TABLE t1,t2;
In the above 4 cases, the same t1 is dropped and inserted multiple times, you can create t1 just once and reuse.

2022-08-24 19:59 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +DROP TABLE t1,t2;
Again, in the above 3 cases, the same t1 is dropped and inserted multiple times, you can create t1 just once and reuse.

2022-08-24 19:59 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +DROP TABLE t1,t2;
Reuse t1 in the above 2 cases.

2022-08-24 19:59 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +
Please reuse t1 in the above 4 scenarios.

2022-08-24 19:59 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +DROP TABLE t1,t2;
Please reuse t1 in the above 3 scenarios.

2022-08-24 19:59 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +DROP TABLE t1,t2;
Please reuse t1 in the above 2 scenarios.

2022-08-25 01:40 UTC, cakebytheoceanLuo commented on mysql-test/columnstore/basic/t/union.test
> +SELECT * FROM (SELECT b FROM t1 UNION SELECT a FROM t1) tu ORDER BY b;
I want to test the duplicate elimination of `UNION` by inserting (1,1) again. The output should be the same in table t1. This test is helpful to check the buffering status in UNION processing.

2022-08-27 04:16 UTC, cakebytheoceanLuo commented
I notice there is a similar case setting the type to DECIMAL: https://github.com/mariadb-corporation/mariadb-columnstore-engine/pull/2526/files#diff-58e39e2454e28831cbe2e09724a4d3754cffe87211028865a93e0ad55df03210R2980-R2985

2022-09-01 19:06 UTC, tntnatbry requested changes

2022-09-01 19:06 UTC, tntnatbry commented on datatypes/mcs_datatype.h
> +    return true;
Please add a line break after this return.

2022-09-01 19:06 UTC, tntnatbry commented on utils/dataconvert/dataconvert.cpp
>            }
Can you please address the above comment?

2022-09-01 19:06 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +INSERT INTO t1 VALUES (-2,2);
You can combine the 3 INSERTs into a single INSERT: `INSERT INTO t1 VALUES (-1, 1), (-1, 1), (-2, 2);`

2022-09-01 19:06 UTC, tntnatbry commented on mysql-test/columnstore/basic/t/union.test
> +SELECT * FROM (SELECT a FROM t2 UNION ALL SELECT a FROM t1) tu ORDER BY a;
We should also add DECIMAL test cases:
- Both sides DECIMAL with same signedness and precision.
- Both sides DECIMAL with same signedness and different precision.
- Both sides DECIMAL with different signedness and same precision.
- Both sides DECIMAL with different signedness and different precision.
- One side DECIMAL and other side integer type. Again, there should be variation in test cases in DECIMAL precision, integer types, and signedness.

2022-09-07 19:00 UTC, tntnatbry approved these changes

2022-09-13 22:55 UTC, merged