[WIP] MCOL-4590 UNION Performance Improvement
mariadb-corporation/mariadb-columnstore-engine pull request #2528
Opened 2022-08-24 09:46 UTC by cakebytheoceanLuo

The Jira issue number for this PR is: [MCOL-4590](https://jira.mariadb.org/browse/MCOL-4590)

2022-09-08 01:00 UTC, tntnatbry requested changes

2022-09-08 01:00 UTC, tntnatbry commented on dbcon/joblist/tupleunion.h
> +  void normalize(const rowgroup::Row& in, rowgroup::Row* out, std::vector<std::function<void(const rowgroup::Row& in, rowgroup::Row* out, uint32_t col)>>& infer_normalize_functions);
Please change `infer_normalize_functions` to camelCase: `inferNormalizeFunctions`.

2022-09-08 01:00 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
>            for (uint32_t i = 0; i < l_tmpRG.getRowCount(); i++, tmpRow.nextRow())
Can you replace `l_tmpRG.getRowCount()` call in the loop with a constant:
```
const uint32_t tmpRGRowCount = l_tmpRG.getRowCount();
```

2022-09-08 01:00 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +          fRowsReturned += (tmpOutputRowCount - l_outputRG.getRowCount());
I don't think this calculation of `fRowsReturned` is correct. What if `tmpOutputRowCount < l_outputRG.getRowCount()`?

Instead, `fRowsReturned` should be moved inside the `if` statement above:

```
if (inserted.second)
{
  copyRow(tmpRow, &outRow);
  const_cast<RowPosition&>(*(inserted.first)) =
    RowPosition(rowMemory.size() - 1, tmpOutputRowCount);
  memDiff += outRow.getRealSize();
  addToOutput(&outRow, &l_outputRG, true, outRGData, tmpOutputRowCount);
  fRowsReturned++;
}
```

2022-09-08 22:41 UTC, tntnatbry requested changes

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +      }
The above `in.isNullValue(i)` check is incorrect. This check cannot be done at the inferring phase as we don't look at the actual column values during inferring but only the column type attributes. This should be removed.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +    out->setIntField(in.getIntField(i), i);
This should be `out->setUintField(in.getIntField(i), i);`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +                result.emplace_back(normalizeIntToXDecimalWithScaleInt64);
The above two functions should be renamed to `normalizeIntToXDecimalInt128` and `normalizeIntToXDecimalInt64` as there is no usage of scale here.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +    out->setUintField(val, i);
I think this should be `out->setIntField(val, i);`. This looks like an error in the original code. Function name should also be changed to `normalizeUntToIntWithScaleInt64`.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +                result.emplace_back(normalizeUintToXDecimalWithScalUint64);
The above two functions should be renamed to `normalizeUintToXDecimalInt128` and `normalizeUintToXDecimalInt64` respectively.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +    out->setUintField(val, i);
This should be `out->setIntField(val, i);`.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +              break;
This case is incorrect. There can be no reference to `in.getUintField(i)` during inferring. You can merge the above two functions into one `normalizeDateToTimestamp` and have the if-else condition inside that function.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +            }
Same as above. This case is incorrect. There can be no reference to `in.getUintField(i)` during inferring. You can merge the above two functions into one `normalizeDatetimeToTimestamp` and have the if-else condition inside that function.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +                    if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT)
This should be `if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT || in.getColTypes()[i] == CalpontSystemCatalog::UFLOAT)`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +                    if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT)
This should be `if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT || in.getColTypes()[i] == CalpontSystemCatalog::UFLOAT)`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +                  if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT)
This should be `if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT || in.getColTypes()[i] == CalpontSystemCatalog::UFLOAT)`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +  }
The following code is duplicated in the above four functions:

```c++
/* have to pick a scale to use for the double. using 5... */
    uint32_t scale = 5;
    uint64_t ival = (uint64_t)(double)(val * datatypes::scaleDivisor<double>(scale));
    const int diff = out->getScale(i) - scale;
    ival = datatypes::applySignedScale<uint64_t>(ival, diff);
```
Can you remove this duplication by creating a common inline function?

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +              if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT)
This should be `if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT || in.getColTypes()[i] == CalpontSystemCatalog::UFLOAT)`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +              if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT)
This should be `if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT || in.getColTypes()[i] == CalpontSystemCatalog::UFLOAT)`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +              if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT)
This should be `if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT || in.getColTypes()[i] == CalpontSystemCatalog::UFLOAT)`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +              if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT)
This should be `if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT || in.getColTypes()[i] == CalpontSystemCatalog::UFLOAT)`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +              if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT)
This should be `if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT || in.getColTypes()[i] == CalpontSystemCatalog::UFLOAT)`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +                if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT)
This should be `if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT || in.getColTypes()[i] == CalpontSystemCatalog::UFLOAT)`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +                if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT)
This should be `if (in.getColTypes()[i] == CalpontSystemCatalog::FLOAT || in.getColTypes()[i] == CalpontSystemCatalog::UFLOAT)`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +  }
The following code is duplicated in the above four functions:
```c++
    /* have to pick a scale to use for the double. using 5... */
    uint32_t scale = 5;
    uint64_t ival = (uint64_t)(double)(val * datatypes::scaleDivisor<double>(scale));
    const int diff = out->getScale(i) - scale;
    ival = datatypes::applySignedScale<uint64_t>(ival, diff);
```

Can you please remove this duplication by creating an inline function? This is the same code that is also duplicated in four more functions above. See my comment at `normalizeXDoubleToIntWithScaleInt64`.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +                result.emplace_back(normalizeLongDoubleToXDecimalWithScaleInt);
Please rename the above two functions to `normalizeLongDoubleToXDecimalInt128` and `normalizeLongDoubleToXDecimalInt` respectively.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +  }
Again, please remove the duplicated code in the above two functions. This is the same code as in the above comment for `normalizeXDoubleToXDecimal`.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +    out->setIntField((int64_t)val, i);
This should be `out->setLongDoubleField(val, i);`

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +  }
Please remove code duplication from the above two functions.

2022-09-08 22:41 UTC, tntnatbry commented on dbcon/joblist/tupleunion.h
> +  void normalize(const rowgroup::Row& in, rowgroup::Row* out, std::vector<std::function<void(const rowgroup::Row& in, rowgroup::Row* out, uint32_t col)>>& normalizeFunctions);
Can you create a typedef for this vector in the global namespace in this .h file and reuse it here as well as in the .cpp?
```c++
using normalizeFunctionsT = std::vector<std::function<void(const rowgroup::Row& in, rowgroup::Row* out, uint32_t col)>>;
```

Also, I think `normalizeFunctions` should be a const ref here:
```c++
void normalize(const rowgroup::Row& in, rowgroup::Row* out, const normalizeFunctionsT& normalizeFunctions);
```

2022-09-09 17:58 UTC, tntnatbry requested changes

2022-09-09 17:58 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +    out->setLongDoubleField((int64_t)val, i);
The typecast to `int64_t` should be removed:
```c++
out->setLongDoubleField(val, i);
```

2022-09-09 17:58 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +    for (i = 0; i < out->getColumnCount(); i++)
Can you add a linebreak before the `for` statement?

2022-09-09 17:58 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +  void normalizeIntToStringNoScale(const Row& in, Row* out, uint32_t i)
There are two linebreaks before this function, please fix.

2022-09-09 17:58 UTC, tntnatbry commented on dbcon/joblist/tupleunion.cpp
> +  void normalizeXDoubleToLongDouble(const Row& in, Row* out, uint32_t i)
There are two linebreaks before this function, please fix.

2022-09-09 20:37 UTC, tntnatbry approved these changes

2022-09-10 11:11 UTC, cakebytheoceanLuo commented
# Experiment

## Dataset

## Hardware Configuration

AWS

## Performance Without This PR

```
Latency histogram (values are in milliseconds)
       value  ------------- distribution ------------- count
    2828.869 |***                                      1
    2880.269 |******                                   2
    2932.602 |***********                              4
    2985.887 |**************                           5
    3040.139 |*******************************          11
    3095.377 |***********************                  8
    3151.619 |***********************                  8
    3208.883 |*******************************          11
    3267.187 |*************************************    13
    3326.551 |**************************************** 14
    3386.993 |**************************               9
    3448.533 |*****************                        6
    3511.192 |*********                                3
    3574.989 |***                                      1
    3639.945 |*********                                3
    3706.081 |***                                      1
 
SQL statistics:
    queries performed:
        read:                            100
        write:                           0
        other:                           0
        total:                           100
    transactions:                        100    (0.31 per sec.)
    queries:                             100    (0.31 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          322.9365s
    total number of events:              100

Latency (ms):
         min:                                 2831.68
         avg:                                 3229.35
         max:                                 3707.17
         95th percentile:                     3511.19
         sum:                               322934.52

Threads fairness:
    events (avg/stddev):           100.0000/0.00
    execution time (avg/stddev):   322.9345/0.00
```

## Performance With This PR


```
Latency histogram (values are in milliseconds)
       value  ------------- distribution ------------- count
    1280.934 |*************************                30
    1304.208 |**************************************** 48
    1327.905 |*********                                11
    1352.033 |****                                     5
    1376.599 |**                                       2
    1401.611 |*                                        1
    1427.078 |*                                        1
    1453.007 |*                                        1
    1771.289 |*                                        1
 
SQL statistics:
    queries performed:
        read:                            100
        write:                           0
        other:                           0
        total:                           100
    transactions:                        100    (0.76 per sec.)
    queries:                             100    (0.76 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          131.2332s
    total number of events:              100

Latency (ms):
         min:                                 1285.18
         avg:                                 1312.31
         max:                                 1768.78
         95th percentile:                     1376.60
         sum:                               131231.23

Threads fairness:
    events (avg/stddev):           100.0000/0.00
    execution time (avg/stddev):   131.2312/0.00
```

2022-09-14 16:46 UTC, merged

2023-01-28 16:25 UTC, Hinal-Srivastava commented
Hello,
I am interested in contributing to this project. Can you please tell me some resources to get started and also guide me towards some first timer tasks? 
Thank you! Looking forward to hearing from you

2023-01-29 12:17 UTC, drrtuy commented
Hi @Hinal-Srivastava,
I am glad to hear that. Could you get in touch with me in [Zulip](https://mariadb.zulipchat.com/#narrow/stream/118759-general/topic/ColumnStore)?