Online algorithm for regr_sxy
mariadb-corporation/mariadb-columnstore-engine pull request #2554
Opened 2022-09-01 17:55 UTC by mariadb-AndreyPiskunov

This is the online algorithm for `regr_sxy`. It does 2 things: improves precision of `regr_sxy` and seemingly resolves the issues with different test results for arm and x86 in regresion.

2022-09-01 18:54 UTC, dhall-MariaDB commented
dropValue is need in order for the function to work as a Window Function. It should reverse the effect of nextValue for the specified value. Please add this back in.

2022-09-30 10:07 UTC, drrtuy approved these changes
LGTM

2022-09-30 10:09 UTC, mariadb-LeonidFedorov requested changes
Arm regression should be fixed

2022-09-30 15:11 UTC, mariadb-LeonidFedorov approved these changes

2022-09-30 15:26 UTC, merged