MCOL-5438 COUNT() in math causes SEGV
mariadb-corporation/mariadb-columnstore-engine pull request #2755
Opened 2023-03-02 18:49 UTC by drrtuy

2023-03-03 10:06 UTC, tntnatbry commented
@drrtuy Please also create this PR for develop.

2023-03-03 11:35 UTC, drrtuy commented
@tntnatbry I think you meant develop-2302

2023-03-03 11:59 UTC, denis0x0D approved these changes

2023-03-03 11:59 UTC, denis0x0D commented on utils/rowgroup/rowgroup.h
> +  ;
Nit remove empty operator

2023-03-03 11:59 UTC, denis0x0D commented on utils/dataconvert/dataconvert.h
> -const std::string columnstore_big_precision[20] = {"9999999999999999999",
Interesting, we had a string array in header =)

2023-03-03 12:05 UTC, denis0x0D requested changes
MTR tests fails

2023-03-03 15:43 UTC, tntnatbry commented
@drrtuy Yes that's what I meant, sorry, develop-23.02.

2023-03-09 12:46 UTC, drrtuy commented on utils/rowgroup/rowgroup.h
> +  ;
Done

2023-03-10 10:09 UTC, mariadb-LeonidFedorov submitted a review, later dismissed

2023-03-10 10:28 UTC, mariadb-LeonidFedorov approved these changes

2023-03-10 10:58 UTC, merged