MCOL-4530: toCppCode() method for ParseTree and TreeNode
mariadb-corporation/mariadb-columnstore-engine pull request #2777
Opened 2023-03-16 18:17 UTC by mariadb-AndreyPiskunov

For creating proper testing environment for MCOL-4530.

2023-03-21 13:49 UTC, mariadb-LeonidFedorov requested changes, later dismissed

2023-03-21 13:49 UTC, mariadb-LeonidFedorov commented on dbcon/execplan/constantcolumn.h
> +  ConstantColumn(const string& constval, int tyoe, const string& data);
no need in this ctor

2023-03-21 13:50 UTC, mariadb-LeonidFedorov commented on dbcon/execplan/filter.h
> +#include <unordered_set>
do we need it?

2023-03-21 13:53 UTC, mariadb-LeonidFedorov commented on dbcon/execplan/rowcolumn.h
> +  RowColumn(std::vector<SRCP> columnVec, const uint32_t sessionID = 0);
please remove

2023-03-21 13:54 UTC, mariadb-LeonidFedorov commented on dbcon/execplan/rowcolumn.h
> +  RowColumn(std::vector<SRCP> columnVec, const uint32_t sessionID = 0);
or implement

2023-03-21 19:10 UTC, mariadb-AndreyPiskunov commented on dbcon/execplan/constantcolumn.h
> +  ConstantColumn(const string& constval, int tyoe, const string& data);
Removed

2023-03-21 19:10 UTC, mariadb-AndreyPiskunov commented on dbcon/execplan/filter.h
> +#include <unordered_set>
No, I removed all unnecessary includes.

2023-03-21 19:11 UTC, mariadb-AndreyPiskunov commented on dbcon/execplan/rowcolumn.h
> +  RowColumn(std::vector<SRCP> columnVec, const uint32_t sessionID = 0);
I chose to implement.

2023-03-22 04:50 UTC, mariadb-LeonidFedorov commented on dbcon/execplan/outerjoinonfilter.cpp
> +
NIT: extra empty string

2023-03-22 04:52 UTC, mariadb-LeonidFedorov commented
Please check and fix clang build errors: It's Debian and Ubuntu 20 in builds.
Also we see test001 is not passing here( why? )

2023-03-22 07:59 UTC, mariadb-SergeyZefirov approved these changes
I like the result very much.

2023-03-22 16:12 UTC, mariadb-AndreyPiskunov commented on dbcon/execplan/outerjoinonfilter.cpp
> +
removed

2023-03-22 20:25 UTC, merged