Fix disk-based distinct aggregation. (E.g. queries like `AGG(DISTINCT ...)` and `AGG(DISTINCT ...) ... GROUP BY ...`).
mariadb-corporation/mariadb-columnstore-engine pull request #2985
Opened 2023-10-05 09:15 UTC by phoeinx

Description to be added.

2023-10-08 11:28 UTC, drrtuy requested changes
Nice patch @phoeinx . I put some comments so plz address them.

2023-10-08 11:28 UTC, drrtuy commented on utils/rowgroup/rowstorage.cpp
> +      fLRU->remove(rgid);  // TODO: why? if we are compeletly dissolving this storage, what does it help?
This call cleans the memory marked as freed. Otherwise control flow frees all the memory at once when it finishes the processing that is not a concurrent-query-friendly behavior.

2023-10-08 11:28 UTC, drrtuy commented on utils/rowgroup/rowaggregation.cpp
> +  fAggregator->finalAggregation();  // TODO: Perhaps move somewhere else?
You are right. I suggest to add a wrapper method in RowAggregationDistinct to call it in TAS control flow.

2023-10-08 11:28 UTC, drrtuy commented on utils/rowgroup/rowaggregation.cpp
> +  while (dynamic_cast<RowAggregationUM*>(fAggregator.get())->nextOutputRowGroup())
There at least two points in the existing code that don't look right. 
Dynamic cast traverses classes hierarchy every time it is called so I suggest you to run it once.
It is correct to check if dynamic_cast is successful before one uses it. I mean, I see there is an implicit invariant telling fAggregator is always RowAggregationUM but in future this might become a false statement.

2023-10-08 11:28 UTC, drrtuy commented on utils/rowgroup/rowstorage.cpp
> +  bool getNextOutputRGData(std::unique_ptr<RGData>& rgdata)
This method is a close replica of 
```
bool getNextRGData(std::unique_ptr<RGData>& rgdata, std::string& fname)
```
I suggest to separate the common code into methods so future changes affects both this method and  getNextRGData mentioned.

2023-10-08 11:28 UTC, drrtuy commented on utils/rowgroup/rowaggregation.cpp
> +  bool more = fRowAggStorage->getNextOutputRGData(fCurRGData);
~An optional suggestion is to leverage std::option<unique_ptr<RGData>> here. c++23 enables a monadic flow based on option. 
I suggest to apply this despite the fact that all other methods use bool to signal the state of a stream.~

2023-10-08 11:28 UTC, drrtuy commented on utils/rowgroup/rowaggregation.cpp
> +  while (dynamic_cast<RowAggregationUM*>(fAggregator.get())->nextOutputRowGroup())
Every dynamic_cast costs a lot, so I suggest to cast it only once. I also suggest to check dynamic_cast result before the cast is used.

2023-11-02 14:40 UTC, phoeinx commented on utils/rowgroup/rowstorage.cpp
> +  bool getNextOutputRGData(std::unique_ptr<RGData>& rgdata)
will do

2024-07-02 17:25 UTC, closed without merging