Mcol 5568 error for invalid conversion
mariadb-corporation/mariadb-columnstore-engine pull request #2987
Opened 2023-10-06 12:57 UTC by mariadb-SergeyZefirov

A smallest fix for our inability to detect overflows in the query results.

2023-10-10 12:59 UTC, mariadb-SergeyZefirov commented
Corresponding changes in regression suite: https://github.com/mariadb-corporation/mariadb-columnstore-regression-test/pull/347

2023-10-10 19:37 UTC, drrtuy commented on dbcon/execplan/arithmeticoperator.h
> +        int128_t x, y;
We have TSUInt64 type that I suggest to improve with math result overflow detection so the code can be reused in future if needed.

2023-10-10 19:39 UTC, drrtuy commented on dbcon/execplan/arithmeticoperator.h
> +          x = (int128_t)lop->getIntVal(row, isNull);
Did you check if this assignment generates MOVDQA, MOVDQU or MOV?
If it is MOVDQA and getIntValue dst is aligned by 8 bytes there will be SEGV here.

2023-10-10 19:40 UTC, drrtuy commented on dbcon/execplan/arithmeticoperator.h
> +          x = (int128_t)lop->getUintVal(row, isNull);
```suggestion
          x = static_cast<int128_t(lop->getUintVal(row, isNull));
```

2023-10-10 19:44 UTC, drrtuy commented on mysql-test/columnstore/basic/r/MCOL-5568-out-of-range.result
> +SELECT indemnity_paid, n_clms, (indemnity_paid + 9) + n_clms FROM test_mult;
I would appreciate if you extend the code and the examples for combinations of: smaller unsigned SQL datatypes, e.g. UBINT, USMALLINT, UTINYINT, *,/ operations and a signed type as the second argument.

2023-10-10 19:45 UTC, drrtuy requested changes
Plz address the comments and the one I shared in Slack.

2023-10-16 13:54 UTC, drrtuy approved these changes
utACK

2023-10-16 13:55 UTC, merged

2023-10-16 13:59 UTC, mariadb-LeonidFedorov commented
PR should be duplicated for branch `stable-23.10`