MCOL-5624: wrong config option stable
mariadb-corporation/mariadb-columnstore-engine pull request #3087
Opened 2023-12-26 11:13 UTC by mariadb-LeonidFedorov

…o be required to start mariadb server

2023-12-26 12:05 UTC, mariadb-AlanMologorsky approved these changes
LGTM

2023-12-27 06:47 UTC, drrtuy requested changes
Double check if this must be `loose_` but not `loose-`.
See [this](https://www.percona.com/blog/using-the-loose_-option-prefix-in-my-cnf/) for details.

2023-12-27 10:42 UTC, mariadb-LeonidFedorov commented
> Double check if this must be `loose_` but not `loose-`. See [this](https://www.percona.com/blog/using-the-loose_-option-prefix-in-my-cnf/) for details.

I prefer our own documentation https://mariadb.com/kb/en/mariadbd-options/#-loose-
And I have tested modified name option against corresponding value for started server

2023-12-27 13:32 UTC, drrtuy approved these changes

2023-12-27 13:32 UTC, merged