MCOL-5133: Stage1 to stand alone cli tool.
mariadb-corporation/mariadb-columnstore-engine pull request #3378
Opened 2024-12-27 13:02 UTC by mariadb-AlanMologorsky

[add] cluster api client class
[fix] cli cluster_app using cluster api client

2025-02-20 16:41 UTC, drrtuy commented on cmapi/mcs_cluster_tool/cluster_app.py
> +    resp = client.shutdown_cluster({'in_transaction': True})
How much time does the shutdown_cluster wait till it returns?

2025-02-20 16:41 UTC, drrtuy commented on cmapi/mcs_cluster_tool/cluster_app.py
> +    resp = client.shutdown_cluster({'in_transaction': True})
Does it take user-specified graceful timeouts into account or this logic is expressed in a different manner?

2025-02-20 16:42 UTC, drrtuy commented on cmapi/cmapi_server/managers/transaction.py
> +                    defaults to 300.0 (TRANSACTION_TIMEOUT)
```suggestion
                    defaults to TRANSACTION_TIMEOUT
```

2025-02-20 16:48 UTC, drrtuy commented on cmapi/cmapi_server/constants.py
> +REQUEST_TIMEOUT: float = 330.0  # 5,5 minutes
We need to experiment but to me these values are method-specific, e.g. `shutdown_cluster` should have it equal to graceful_timeout, `start_cluster` can have it as 330 secs,  but `set_mode`, `get_status`, should have lower values, so if it fails, it fails faster(30 secs should be enough). `load_s3` on contrary must have huge value here.

2025-02-20 16:49 UTC, drrtuy requested changes
Plz address the comments

2025-03-11 12:50 UTC, mariadb-AlanMologorsky commented on cmapi/mcs_cluster_tool/cluster_app.py
> +    resp = client.shutdown_cluster({'in_transaction': True})
Fixed after discussing. Added timeouts.

2025-03-11 12:51 UTC, mariadb-AlanMologorsky commented on cmapi/cmapi_server/managers/transaction.py
> +                    defaults to 300.0 (TRANSACTION_TIMEOUT)
Fixed in another request.

2025-03-11 12:52 UTC, mariadb-AlanMologorsky commented on cmapi/cmapi_server/constants.py
> +REQUEST_TIMEOUT: float = 330.0  # 5,5 minutes
Fixed, added timeouts.

2025-03-12 11:21 UTC, drrtuy approved these changes
untested ACK

2025-03-12 11:21 UTC, merged