MCOL-3357
mariadb-corporation/mariadb-columnstore-engine pull request #894
Opened 2019-10-07 18:18 UTC by benthompson15

2019-10-07 22:03 UTC, pleblanc1976 requested changes
Doesn't implement the listener interface.  Should be mainly a cut & paste job to make it do that.  Listener pattern -> better encapsulation & more maintainable.

2019-10-07 22:03 UTC, pleblanc1976 commented on storage-manager/src/Cache.cpp
> +        size_t configCacheValue = stoul(stmp);
stoul() only handles unsigned 64-bit, might want to make that match the size_t type.

2019-10-08 07:16 UTC, LinuxJedi commented on storage-manager/src/Cache.cpp
> +        size_t configCacheValue = stoul(stmp);
Did you mean unsigned 32-bit? stoull() is the 64-bit one.

2019-10-08 13:52 UTC, pleblanc1976 commented on storage-manager/src/Cache.cpp
> +        size_t configCacheValue = stoul(stmp);
Sry, typo, yes, stoull() is what you're after Ben.

2019-10-08 18:25 UTC, closed without merging