MCOL-3563: fix compiler warnings / type errors.
mariadb-corporation/mariadb-columnstore-engine pull request #918
Opened 2019-10-31 20:27 UTC by benthompson15

A previous commit made posix::read changed return value
from bool to int. However some callers still expected
bool and compared a bool<0 which is always false.

2019-11-21 20:51 UTC, pleblanc1976 requested changes
- opentask and pingtask need the bool->int fix
 - not sure the unit test is doing what it's supposed to do, take another look at that please.  At minimum add some english to describe why it's reading from closed sockets, etc.  If it works as intended, nobody would figure this out.  :D

2019-11-25 20:49 UTC, LinuxJedi approved these changes

2019-12-02 16:18 UTC, pleblanc1976 requested changes
Looks OK except for the unit test changes.

2019-12-02 16:18 UTC, pleblanc1976 commented on storage-manager/src/unit_tests.cpp
> +        assert(err == -1);
still confused about what we're doing with the close-recv bit.  Closing a socket and then reading from it will always return -1, doesn't say anything about the SM code.

IIRC, we're verifying correct behavior by 'manually' watching a log file.  If we don't want to automate that part (too much trouble is a totally valid reason right now), could you add a printout here telling the user what to look for?

2019-12-02 16:18 UTC, pleblanc1976 commented on storage-manager/src/unit_tests.cpp
> +        assert(err == -1);
same comment as above

2019-12-02 16:18 UTC, pleblanc1976 commented on storage-manager/src/unit_tests.cpp
> +        assert(err == -1);
Looks like the mods to the unit test are mainly this, which is only checking that reading from a closed socket returns -1 AFAICT.

2019-12-04 20:08 UTC, pleblanc1976 approved these changes

2019-12-04 20:08 UTC, merged